config/routes.rb
Rails.application.routes.draw do
  root to: 'bugs#index'
  devise_for :users

  resources :bugs do
    resources :comments do
      resources :replies
    end
    collection do
      get :active
      get :archive
      get :processing
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  belongs_to :bug

  validates :body, :comment_id, :bug_id, :user_id, presence: true 
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: %i[ show edit update destroy ]

  # GET /replies or /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1 or /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @bug = Bug.find(params[:bug_id])
    @comment = @bug.comments.find(params[:comment_id])
    @reply = @comment.replies.build
  end

  # GET /replies/1/edit
  def edit
    set_reply
    @bug = @reply.bug
    @comment = @reply.comment
  end

  # POST /replies or /replies.json
  def create
    @bug = Bug.find(params[:bug_id])
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.new(reply_params)
    @reply.user_id = current_user.id
    @reply.bug_id = @bug.id

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @bug, notice: "Reply was successfully created." }
        format.json { render :show, status: :created, location: @reply }
      else

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1 or /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to bugs_path, notice: "Reply was successfully updated." }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1 or /replies/1.json
  def destroy
    @bug = Bug.find(params[:bug_id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to bug_path(@bug), notice: "Reply was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reply_params
      params.require(:reply).permit(:body, :user_id, :bug_id, :comment_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_with(model: [@bug, @comment, @comment.replies.build]) do |form| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
        <% reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id %>
  </div>

  <% user_id = current_user.id %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :bug_id %>
    <%= form.text_field :bug_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/_reply.html.erb
<% if reply.persisted? %>
    <% @user = User.find(reply.user_id).email %>
    <% @comment = Comment.find(reply.comment_id) %>
    <div>
        <small><%= @user + " replied"%></small>
        <br>
        <strong><%= reply.body %></strong>
        <br>
        <small><%= time_ago_in_words(reply.created_at) + " ago..." %></small>
        <% if current_user.email == @user %>
                <section>
                    <%= link_to 'delete', bug_comment_reply_path(@bug.id, @comment.id, reply), data: { confirm: 'Are you sure?' }, method: :delete %>
                    
                    <%= link_to 'edit', edit_bug_comment_reply_path(@bug.id, @comment.id, reply) %>
                </section>
        <% end %>
        <br>
    </div>

<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>
<% bug = Bug.find(params[:bug_id]) %>
<% comment = bug.comments.find(params[:comment_id]) %>
<% reply = comment.replies.find(params[:id])%>
<div>
  <p>Comment</p>
    <%= form_with(model: [bug, comment, reply]) do |form| %>
      <div>
        <%= form.label 'Edit Reply' %>
        <% user_id = current_user.id %>
        <%= form.hidden_field :user_id %>
        <%= form.hidden_field :bug_id %>
        <%= form.hidden_field :comment_id %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>
      <%= form.submit 'Update' %>
    <% end %>
</div>

<%= link_to 'Back', bug_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Comment</th>
      <th>User</th>
      <th>Bug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.body %></td>
        <td><%= reply.comment_id %></td>
        <td><%= reply.user_id %></td>
        <td><%= reply.bug_id %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', bug: @bug, comment: @comment, reply: @reply %>

<%= link_to 'Back', bug_comments_path(@bug) %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @reply.body %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user_id %>
</p>

<p>
  <strong>Bug:</strong>
  <%= @reply.bug_id %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>