config/routes.rb
Rails.application.routes.draw do
  root to: 'bugs#index'
  devise_for :users

  resources :bugs do
    resources :comments do
      resources :replies
    end
    collection do
      get :active
      get :archive
      get :processing
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bug

  has_many :replies, dependent: :destroy

  validates :body, :bug_id, :user_id, presence: true 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @bug = Bug.find(params[:id])
    @comment = @bug.comments.find(params[:bug_id])
  end

  # POST /comments or /comments.json
  def create
    @bug = Bug.find(params[:bug_id])
    @comment = @bug.user.comments.new(comment_params)
    @comment.user_id = current_user.id
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @bug, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to bugs_path, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @bug = Bug.find(params[:id])
    @comment = @bug.comments.find(params[:comment_id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to bug_path, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :bug_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.persisted? %>
    <% @user = User.find(comment.user_id).email %>
    <% @bug = Bug.find(comment.bug_id) %>
    <div>
        <small><%= time_ago_in_words(comment.created_at) + " ago..." %></small>
        <br>
        <small><%= @user + " posted"%></small>
        <br>
        <strong><%= comment.body %></strong>
            <% if current_user.email == @user %>
                <section>
                    <%= link_to 'delete', bug_comment_path(comment), data: { confirm: 'Are you sure?' }, method: :delete %>
                    <%= link_to 'edit', edit_bug_comment_path(comment) %>
                </section>
            <% end %>
    </div>

<% end %>

app/views/comments/_form.html.erb
<% if @bug %>
  <%= form_with(model: [@bug, @bug.comments.build]) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
    <% user_id = current_user.id %>
    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id %>
    </div>

    <div class="field">
      <%= form.label :bug_id %>
      <%= form.text_field :bug_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<% bug = Bug.find(params[:id]) %>
<% comment = bug.comments.find(params[:bug_id]) %>
<div>
  <p>Comment</p>
    <%= form_with(model: [bug, comment]) do |form| %>
      <div>
        <%= form.label 'Edit Comment' %>
        <% user_id = current_user.id %>
        <%= form.hidden_field :user_id %>
        <%= form.hidden_field :bug_id %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>
      <%= form.submit 'Update' %>
    <% end %>
</div>

<%= link_to 'Back', bug_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Bug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.bug_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_bug_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', bugs_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Bug:</strong>
  <%= @comment.bug_id %>
</p>

<%= link_to 'Edit', edit_bug_comment_path(@comment) %> |
<%= link_to 'Back', bugs_path %>