config/routes.rb
Rails.application.routes.draw do
  root to: 'bugs#index'
  devise_for :users

  resources :bugs do
    resources :comments do
      resources :replies
    end
    collection do
      get :active
      get :archive
      get :processing
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :delete_all
    has_many :replies, dependent: :delete_all

    enum priority: { low: 0, medium: 1, high: 2 }
    enum status: { active: 0, in_progress: 1, solved: 2 }, _default: 'active'
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  #before_action :require_user!, only: %i(new create edit update)
  #before_action :set_bug, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /bugs or /bugs.json
  def index
    @bugs = Bug.all
    render :index
  end

  # GET /bugs/1 or /bugs/1.json
  def show
    @bug = Bug.find(params[:id])
    render :show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
    render :new
  end

  # GET /bugs/1/edit
  def edit
    @bug = Bug.find(params[:id])
    render :edit
  end

  # app/controllers/bugs_controller.rb
def create
  @bug = current_user.bugs.new(bug_params)
  @bug.finder = current_user.email

  respond_to do |format|
    if @bug.save
      format.html { redirect_to bug_path(@bug), notice: "Bug was successfully created." }
      format.json { render :show, status: :created, location: @bug }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @bug.errors, status: :unprocessable_entity }
    end
  end
end


  # PATCH/PUT /bugs/1 or /bugs/1.json
  def update
    @bug = Bug.find(params[:id])

    @bug.fixer = current_user.email
    
    # Store the current fixer before the update
    previous_fixer = @bug.fixer

    respond_to do |format|
      if @bug.update(bug_params)
        set_fixer_if_in_progress(previous_fixer)
        format.html { redirect_to bug_url(@bug), notice: "Bug was successfully updated." }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1 or /bugs/1.json
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy

    respond_to do |format|
      format.html { redirect_to bugs_url, notice: "Bug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bug_params
      params.require(:bug).permit(:project, :path, :priority, :description, :finder, :status, :fixer)
    end


    def set_fixer_if_in_progress(previous_fixer)
      # Check if the status has changed to 'in_progress' and update the fixer
      if @bug.status == 'in_progress' && @bug.fixer != previous_fixer
        @bug.update(fixer: current_user.email)
      end
    end

end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_with(model: bug) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
        <% bug.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project %>
    <%= form.text_area :project %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_area :path %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Bug.priorities.keys.map { |priority| [priority.humanize, priority] } %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Bug.statuses.keys.map { |status| [status.humanize, status] } %>
  </div>

  <%# Display the current fixer value (if it exists) %>
  <% if bug.fixer.present? %>
    <div class="field">
      <%= form.label :fixer %>
      <%= bug.fixer %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bugs/active.html.erb
<h1>Active Bugs</h1>


<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
      <th>Status</th>
      <th>Priority</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% Bug.all.each do |bug| %>
      <% if bug.status == "active" %>
        <tr>
          <td><%= bug.project %></td>
          <td><%= bug.description %></td>
          <td id="status"><%= bug.status %></td>
          <td id="priority"><%= bug.priority %></td>
          <td><%= link_to 'Show', bug %></td>
          <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
          <td><%= link_to 'Delete', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<section>
  <%= link_to 'Back', bugs_path %>
</section>

app/views/bugs/archive.html.erb
<h1>Archived Bugs</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Bug.all.each do |bug| %>
      <% if bug.status == true %>
        <tr>
          <td><%= bug.path %></td>
          <td><%= bug.description %></td>
          <td><%= bug.status %></td>
          <td><%= link_to 'Show', bug %></td>
          <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
          <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', bugs_path %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<section>
    <%= render 'form', bug: @bug %>

    <%= link_to 'Cancel', @bug %>
</section>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

  <h1>Bug Tracker</h1>

  <div class="box">
    <%= link_to 'New Bug', new_bug_path %>
  </div>
  <div class="box">
    <%= link_to 'Active', active_bugs_path %>
  </div>
  <div class="box">
    <%= link_to 'Archive', archive_bugs_path %>
  </div>
  <div class="box">
    <%= link_to 'Processing', processing_bugs_path %>
  </div>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<div class="form">
    <%= render 'form', bug: @bug %>
</div>

<section>
    <%= link_to 'Back', bugs_path %>
</section>

app/views/bugs/processing.html.erb
<h1>Bugs in Process</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
      <th>Status</th>
      <th>Priority</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% Bug.all.each do |bug| %>
      <% if bug.status == "in_progress" %>
        <tr>
          <td><%= bug.project %></td>
          <td><%= bug.description %></td>
          <td id="status"><%= bug.status %></td>
          <td id="priority"><%= bug.priority %></td>
          <td><%= link_to 'Show', bug %></td>
          <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
          <td><%= link_to 'Delete', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<section>
  <%= link_to 'Back', bugs_path %>
</section>

app/views/bugs/show.html.erb
<section>
  <p id="notice"><%= notice %></p>

  <div class="bug">
    <h2>
      <strong>Project:</strong>
      <%= @bug.project %>
    </h2>

    <p>
      <strong>Path:</strong>
      <%= @bug.path %>
    </p>

    <p>
      <strong>Status:</strong>
      <span id="status"><%= @bug.status %></span>
    </p>

    <p>
      <strong>Priority:</strong>
      <span id="priority"><%= @bug.priority %></span>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @bug.description %>
    </p>

    <p>
      <strong>Found by:</strong>
      <%= @bug.finder %>
    </p>

    <% if @bug.fixer %>
      <p>
        <strong>Assigned to:</strong>
        <%= @bug.fixer %>
      </p>
    <% end %>
  </div>

  <%= link_to 'Back', bugs_path %>
  <%= link_to 'Edit', edit_bug_path(@bug) %>
</section>

<section>
<h2>Comments</h2>
  <div class="comment">
    <%= form_with(model: [@bug, @bug.comments.build]) do |form| %>
      <div>
        <%= form.label :body, 'New Comment', for: 'comment_body' %>
        <%= form.hidden_field :user_id %>
        <%= form.hidden_field :bug_id %>
        <%= form.text_area :body, id: 'comment_body', class: 'form-control' %>
      </div>
      <%= form.submit 'Post' %>
    <% end %>
  </div>

  <div class="comment">
    <% @bug.comments.order("updated_at DESC").each do |comment| %>
      <div class="comment-body">
        <%= render partial: 'comments/comment', locals: { comment: comment } %>
      </div>

      <button class="reply-button">Reply</button>
      
      <div class="reply" id="reply" style="display: none;">
        <%= form_with(model: [@bug, comment, comment.replies.build]) do |form| %>
          <div>
            <%= form.label :body, 'New Reply', for: 'reply_body' %>
            <%= form.hidden_field :bug_id %>
            <%= form.hidden_field :comment_id %>
            <%= form.hidden_field :user_id %>
            <%= form.text_area :body, id: 'reply_body', class: 'form-control' %>
          </div>
          <%= form.submit 'Post Reply' %>
        <% end %>
      </div>
      <div class="replies">
        <%= render partial: 'replies/reply', collection: comment.replies %>
      </div>
    <% end %>
  </div>

</section>